### ISSUE TITLE
Traders

### ISSUE THREAD

**Issue by massimilianodelliubaldini** [ArchipelaGOAL/Archipelago#10]
### What feature would you like to see?

Currently, all traders in the game are out-of-logic until you can acquire the total number of orbs to pay them all at once (1530). That shoves them all behind the last third/quarter of the game, which is a little awkward. 

However, if a trader has a key item you need for progression, but you spent all your orbs on other traders, don't have enough orbs, and can't acquire any more from your current state, you are now hard-locked out of completion. This can happen in both hub 1 and hub 3. We want to avoid this at all costs.

But maybe there's some idea out there where we can incrementally make the traders in logic while avoiding a hard-lock?

**Comment by massimilianodelliubaldini** [comment]
~~Possibly~~ Definitely affected by #9.

**Comment by jacobmix** [comment]
A fix could be to make all trades the same price, and any gains outside power cells are gained from having a specific number of power cells, tied to another item in some way or be their own check or something.
This does take away some of the dynamic of where to spend your orbs, if to save up, ect. But makes it impossible to get stuck.

**Comment by massimilianodelliubaldini** [comment]
I think we're gonna close this one out. I haven't thought of a better idea other than making the trades progressive. However, even with that there was the risk of paying off more expensive trades (the oracles) before the cheaper trades (the citizens), so you'd get 2 checks (e.g. Sandover Oracle 1 and 2) rather than the 3 you could have afforded (Uncle, Mayor, and Oracle 1) if you spent more wisely. If that the 3rd check was your unwall, you've now lost it forever. 

Now I'm not just closing this out with nothing to show for it. I did make the trades configurable options: Citizen Orb Trade Amount and Oracle Orb Trade Amount. You can make these both 0 and have them immediately be in-logic, or keep them default, or crank them both higher, or anything in between. And keeping all the trades locked behind the total calculation of required orbs doesn't prevent a player from trading with them early out-of-logic. 

So either way, I think the problem is effectively _neutralized_, even if I wouldn't call it _solved_.
