### ISSUE TITLE
Bug: When i reload my save i get scout flies, but not power cells

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#17]
### What happened?

When i reload my save i get scout flies, but not power cells.
Updated apworld, and mod on both host, and client from 0.0.2 to 0.0.3
Even if i get new powercells. Once i quit out i lose those as well when i reload the save.
Here's my .archipellago .apsave, and spoiler.txt files:
[AP_05159041708763162666.zip](https://github.com/user-attachments/files/15671129/AP_05159041708763162666.zip)

### What were the expected results?

Powercells getting accounted for.

### Software

While playing

**Comment by jacobmix** [comment]
Closing. Need to load save. THEN connect. My bad.

**Comment by massimilianodelliubaldini** [comment]
This will eventually be true of scout flies as well as power cells (hopefully fixing #6).
