### ISSUE TITLE
Add text showing items sent/received 

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#19]
### What feature would you like to see?

Showing items sent/received, so you'll know who sent you what, and what you're sending to who, All in-game.

**Comment by massimilianodelliubaldini** [comment]
![image](https://github.com/user-attachments/assets/b59ea6e5-f695-4bba-bd7d-8d6563aee6a0)
![image](https://github.com/user-attachments/assets/76141a90-6bb7-45ee-8dc5-a824334b5bb8)

The normal HUD shows the last item you received, while the alternate HUD's show the last item you sent. In either mode, the text changes from green to blue if it's an item you found for yourself.
