### ISSUE TITLE
Make items sync when loading save

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#20]
### What feature would you like to see?

Right now you first have to connect AFTER loading a save to fully sync which is different than most other games.
Detecting when loading a save, and syncing then somehow might streamline things, and remove confusion.

**Comment by massimilianodelliubaldini** [comment]
I'm looking into ways to allow the user to ignore the order of operations of connecting to the server and loading the save, so you end up with the correct number of items regardless of which order you do it. 

I _think_ I have a solution, but it's gonna take a little brainstorming. The changes I made to the save/load system is this:

0. You enter the title screen, you have 0 of any item.
1. If you load the save first, it doesn't change your item count (still 0). You then connect to the AP server, and it gives you all of your items. You are now ready.
2. If you connect to the AP server first, it gives you all of your items (you just can't see them on the title screen). You then load the save, which doesn't change your item count. You are now ready.

There are a couple of downsides to this system.

1. You can't really tell when you're done receiving items on the title screen, unlike in game where you have the HUD. 
2. Your item counts will not change when quitting to the menu, or loading another save. If you disconnect the client while the game is still running, and you reconnect, you'll double-receive all your items again.

**Comment by massimilianodelliubaldini** [comment]
@jacobmix If you think the ability to load the save and connect to the server in any order (or even simultaneously) is a good enough solution to this issue, I will mark it for closing in the next release. If not, or you think the title feature as stated should still be implemented, I'll leave this open.
