### ISSUE TITLE
Add completion goal options

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#22]
### What feature would you like to see?

Add goal options so players can pick what do do to complete their run, and release their remaining items. Examples:
Beat the final boss ([Gol and Maia's Precursor robot](https://jakanddaxter.fandom.com/wiki/Gol_and_Maia%27s_Precursor_robot))
100%. (Have 101 Power Cells, and watch the end cutscene)
Have (total) 2000 Precursor Orbs
Have 112 Scout Fly
Catch the Muse

**Comment by massimilianodelliubaldini** [comment]
I picked out the boss fights and connector levels as completion options. It provides a good variety for game length: could be as small as crossing Fire Canyon, or as long as opening the 100 cell door.

```py
class CompletionCondition(Choice):
    """Set the goal for completing the game."""
    display_name = "Completion Condition"
    option_cross_fire_canyon = 69
    option_cross_mountain_pass = 87
    option_cross_lava_tube = 89
    option_defeat_dark_eco_plant = 6
    option_defeat_klaww = 86
    option_defeat_gol_and_maia = 112
    option_open_100_cell_door = 106
    default = 112
```
