### ISSUE TITLE
Bug: LPC slide deaths don't count

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#28]
### What happened?

Lost Precursor city slide deaths don't send any deathlinks

### What were the expected results?

Deathlinks to be sent no matter the death, when, and how.

### Software

While playing

**Comment by massimilianodelliubaldini** [comment]
Jak has unique death handling code while on the LPC slides - found the code and added the usual bits of Deathlink logic to them.
