### ISSUE TITLE
Mod version number in-game

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#31]
### What feature would you like to see?

People seem to be mistaking the mod to be updated when it isn't a lot.
Adding a way to see the mod version number in-game could help users see they're not on the newest version.
Could be done by changing the title-screen logo, a menu item or some text on screen before the player truly starts playing.

**Comment by massimilianodelliubaldini** [comment]
Mod version number can be displayed if you activate Speedrunner Mode.

`Options > Game Options > Miscellaneous > Speedrunner Mode`

![image](https://github.com/ArchipelaGOAL/Archipelago/assets/8584296/c78b1004-c59f-4684-9166-f936d73eca6a)

**Comment by jacobmix** [comment]
Nice. Still need to add a "How to update" section to the setup instructions with this mentioned. (Or update instructions in general)

**Comment by massimilianodelliubaldini** [comment]
Wilco.
