### ISSUE TITLE
Single orb caches move rando issue

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#35]
### What happened?

Precursor orb caches require crouch or any attack move to get the last orb if you get out of it with a single orb left.  
Potential hardlock* if you save, and the last orb in that zone is critical to progression. (*If you don't turn off move rando in settings)
  
Reported by Lezchill on [Discord](https://discord.com/channels/731205301247803413/1138467653552451606/1265277185200095233)

### What were the expected results?

Single precursor orb in the cache still being collectable with no moves unlocked or for it to be accounted for in logic.

### Software

While playing

**Comment by massimilianodelliubaldini** [comment]
Raised the minimum height on the orb cache top so that Jak can walk under it even with 1 orb remaining.
![image](https://github.com/user-attachments/assets/bf896ca0-38a5-4f92-9a56-514f2b52b678)
