### ISSUE TITLE
Bug: Goaling near immediately on starting game

### ISSUE THREAD

**Issue by DiStegro** [ArchipelaGOAL/Archipelago#50]
### What happened?

Game goaled upon reaching an early check. Tested seven times, including overwriting save with empty game, closing everything, then connecting and overwriting that, while connected to a blank AP, while unconnected, and using vanilla OpenGOAL, and deleted all files in 'saves' folder at one point. Finally tested a previously unused save file and still ran into the same issue
This didn't always happen on the first power cell, sometimes it waited until the scout flies just up the road

For what it's worth, goal was Fire Canyon and expected to be very early, but I didn't even seem to get Power Cells for it yet

Seemingly relevant logs in case they help:

Jak1 Logs:
[jak1.2024-09-11T18-25-48.log](https://github.com/user-attachments/files/16967721/jak1.2024-09-11T18-25-48.log)
[jak1.2024-09-11T18-30-43.log](https://github.com/user-attachments/files/16967722/jak1.2024-09-11T18-30-43.log)
[jak1.2024-09-11T18-32-35.log](https://github.com/user-attachments/files/16967723/jak1.2024-09-11T18-32-35.log)
[jak1.2024-09-11T18-33-35.log](https://github.com/user-attachments/files/16967724/jak1.2024-09-11T18-33-35.log)
[jak1.2024-09-11T18-39-10.log](https://github.com/user-attachments/files/16967726/jak1.2024-09-11T18-39-10.log)
[jak1.2024-09-11T18-41-48.log](https://github.com/user-attachments/files/16967727/jak1.2024-09-11T18-41-48.log)
[jak1.2024-09-11T19-00-57.log](https://github.com/user-attachments/files/16967778/jak1.2024-09-11T19-00-57.log)

Jak and Daxter Client Logs:
[JakAndDaxterClient_2024_09_11_18_32_34.txt](https://github.com/user-attachments/files/16967792/JakAndDaxterClient_2024_09_11_18_32_34.txt)
[JakAndDaxterClient_2024_09_11_18_33_34.txt](https://github.com/user-attachments/files/16967793/JakAndDaxterClient_2024_09_11_18_33_34.txt)
[JakAndDaxterClient_2024_09_11_18_39_09.txt](https://github.com/user-attachments/files/16967796/JakAndDaxterClient_2024_09_11_18_39_09.txt)
[JakAndDaxterClient_2024_09_11_18_41_47.txt](https://github.com/user-attachments/files/16967797/JakAndDaxterClient_2024_09_11_18_41_47.txt)
[JakAndDaxterClient_2024_09_11_19_00_57.txt](https://github.com/user-attachments/files/16967799/JakAndDaxterClient_2024_09_11_19_00_57.txt)
[JakAndDaxterClient_2024_09_11_18_25_47.txt](https://github.com/user-attachments/files/16967800/JakAndDaxterClient_2024_09_11_18_25_47.txt)
[JakAndDaxterClient_2024_09_11_18_30_42.txt](https://github.com/user-attachments/files/16967801/JakAndDaxterClient_2024_09_11_18_30_42.txt)

### What were the expected results?

Sending/receiving an item as normal

### Software

While playing

**Comment by massimilianodelliubaldini** [comment]
This was caused by a client/mod version mismatch for other people, and it should be solved if you make sure you have the latest (as of today) APWORLD and ArchipelaGOAL mod.

**Comment by massimilianodelliubaldini** [comment]
@DiStegro Glad it worked out. Keep in mind the OpenGOAL Launcher takes 24 hours to find mod updates, so it's probably best to just wait a day.
