### ISSUE TITLE
Found/sent/received text expanded to more than one item/lines

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#53]
### What feature would you like to see?

Being able to see 3 recent items sent instead of just one.
This could be done with 3 lines, bottom one being the newest.
Maybe even include an option to pick how many messages you want yourself. Something like 1-20 probably.
An option to always show found/sent/received regardless of HUD setting might be nice or tie each to default/global/local/all/off.
Visual: Make a "scrolling up" animation to move lines up when a new line/item get's added to communicate bottom is the newest.
Visual: Make the top line(s) more see-through or set timer (besides newest?) that slowly makes line disappear, refresh on HUD use?

I know there's a few limits to how text is handled in Jak, and the way text is piped to Jak. But hopefully something can be done.

**Comment by massimilianodelliubaldini** [comment]
To be completed by #54 .
