### ISSUE TITLE
Some Scout Fly items names are mismatched 

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#57]
Scout Fly names got switched up after they got changed to their longer versions in a commit.
Commit with the faulty name change: [9bec937](https://github.com/ArchipelaGOAL/Archipelago/commit/9bec9377fd2006d92f1d562d80d17e4393a18fc2#diff-232102219bfff4e110b8e275ffbba3dc1ae63e5e0ba39c54382b6b53518464e8R23)
Discord convo: https://discord.com/channels/731205301247803413/1138467653552451606/1299521647799177306

**Comment by massimilianodelliubaldini** [comment]
Fixed with #58.
