### ISSUE TITLE
Bug: Not receiving death link

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#61]
Some times death links don't work.
Toggling the option in-game seems to fix it.
Discord: [1](https://discord.com/channels/731205301247803413/1138467653552451606/1306989185303052368)

**Comment by massimilianodelliubaldini** [comment]
I have a fix ready to go with the next APWORLD.

**Comment by massimilianodelliubaldini** [comment]
Fixed with https://github.com/ArchipelaGOAL/Archipelago/pull/63
