### ISSUE TITLE
Bug: Won't launch right through the client

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#62]
Some users seem to have issues launching the game even with what should be the right settings set.
The current work around is:
Open OpenGOAL Launcher>Jak1>Features>Mods>ArchipelaGOAL>Advanced>Open Data Folder>Go up a folder to see gk.exe Double click the gk.exe. Inside Jak hit Alt, and in the top bar click: "Debugging">"Reboot In Debug Mode!". Then run the REPL from the ArchipelaGOAL (Advanced) mod page in the OpenGOAL Launcher, and, then run the Jak and Daxter client from the Archipelago Launcher.
Discord: [1](https://discord.com/channels/731205301247803413/1138467653552451606/1306765022210293792)

**Comment by massimilianodelliubaldini** [comment]
Should be fixed with release of ArchipelaGOAL v0.4.1.
