### ISSUE TITLE
Optimize "'Free 7 Scout Flies' Power Cells" for async games

### ISSUE THREAD

**Issue by jacobmix** [ArchipelaGOAL/Archipelago#66]
"'Free 7 Scout Flies' Power Cells" check require the game to be active after receiving the 7 related items.
A way to make it more async friendly would be good so you won't need to boot up Jak just for those checks.
Discord [convo](https://discord.com/channels/731205301247803413/1138467653552451606/1319964001467240449).

**Comment by massimilianodelliubaldini** [comment]
ap-world-dev confirmed there's no way to hand off the responsibility of releasing the 7th scout fly check from the game onto Archipelago itself. Exempt Medic himself confirmed that's generally not desired behavior for Archipelago either way.
