### ISSUE TITLE
Move Randomizer

### ISSUE THREAD

**Issue by massimilianodelliubaldini** [ArchipelaGOAL/Archipelago#7]
### What feature would you like to see?

Add Moves as Items to the randomizer, similarly to the mod "Microtransactions" which locks each of Jak's moves behind a payment of precursor orbs. Instead of orb payments, we would need additional Locations to map them to.

**Comment by massimilianodelliubaldini** [comment]
Here is the list of moves (Items) I am planning to add to the move randomizer. For corresponding locations, I'm planning on mapping them to the orb caches, since there is mod hooks that check when these have been unlocked, so we can use those to tell AP that you checked them.

```
L1 (Crouch)			1	Crouch
					
	L1 + X			2	Crouch Jump
					
	L1 + S			3	Crouch Uppercut
					
L1 (Roll)				4	Roll
					
	L1 + X			5	Roll Jump
					
X						Jump
					
	X + X			6	Double Jump
				
	X + S			7	Jump Dive
					
	X + C			8	Jump Kick
					
S					9	Punch
					
	S + X			10	Punch Uppercut
					
C					11	Kick
```

**Comment by massimilianodelliubaldini** [comment]
I could always use some assistance with mapping out granular subregions of each level in the game, and how one would move from one subregion to another with certain moves at their disposal. So if you want to contribute and have the time, here's some levels that I need maps for. These maps will be translated into logical regions for AP. 

```
Sandover Village
Sentinel Beach
Forbidden Jungle
~~Misty Island~~
Rock Village
Lost Precursor City
Boggy Swamp
Mountain Pass
Volcanic Crater
Snowy Mountain
Spider Cave
Gol and Maia's Citadel
```

So the idea is you use MS Paint or Paint.net, make a bunch of boxes that represent subregions. Each box should have a name, and a short list of the Location checks that are in there (don't forget the aforementioned orb caches). Then a bunch of arrows should link the boxes indicating how you can get from one subregion to another. Each arrow should have a list of moves you can use to get from region A to region B. Remember, some of these are one-way (like falling from a cliff) and some can be two-way (by walking, roll jumping, etc).

Here's one I made for Misty Island, as an example (I was a little sloppy with the movement arrows).

![move-rando-misty-island](https://github.com/ArchipelaGOAL/Archipelago/assets/8584296/ec24c997-80a7-43b9-9156-80f9a9533ab1)

**Comment by jacobmix** [comment]
From lone on Discord:
![image](https://github.com/ArchipelaGOAL/Archipelago/assets/5995327/24a343be-3e11-49f5-8a6c-edc9cdb6888e)
![image](https://github.com/ArchipelaGOAL/Archipelago/assets/5995327/bc9293e2-3420-4132-bd28-a47d572baed9)
![image](https://github.com/ArchipelaGOAL/Archipelago/assets/5995327/91f40b31-d659-4b69-b444-9719ba4ee36d)
![image](https://github.com/ArchipelaGOAL/Archipelago/assets/5995327/00f30520-67b5-447c-ace1-e1c9654dba1c)
![image](https://github.com/ArchipelaGOAL/Archipelago/assets/5995327/8ff6ff30-a884-415a-9fd3-f3ee4b62224e)
![image](https://github.com/ArchipelaGOAL/Archipelago/assets/5995327/303341f1-e8d5-4216-8099-d2fd0f46b729)
> YE easy : can stand in place, no threat of enemies
> YE medium : need to move away from eco spawn, but have ample time, or there are some mildly threatening enemies
> YE hard : need to move far away from eco spawn and aim quick, or have to deal with a lot of enemies
> YE vhard : reserved for arena battle. Not sure if this is possible in practice

**Comment by jacobmix** [comment]
Also i made a route for Spider Cave:
![Jak1_MoveRando_SpiderCave](https://github.com/ArchipelaGOAL/Archipelago/assets/5995327/f5964de0-afbd-459a-a36a-903d05fa10a4)

**Comment by jacobmix** [comment]
Snowy Mountain visual done:
![Jak1_MoveRando_Snowy](https://github.com/ArchipelaGOAL/Archipelago/assets/5995327/c357f975-1f6b-4583-bd0c-15332fa91c7e)
You can do all the blockers with just roll jump as well.
